[project]
name = "pico"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.5.1",
    "onvif-zeep>=0.2.12",
    "opencv-contrib-python>=5.0.0.93",
    "opencv-python>=5.0.0.93",
    "python-dotenv>=1.2.2",
    "onnxruntime>=1.20.0",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.15.22",
]
